name: Deploy Python CDK
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Node.js (for CDK CLI)
      uses: actions/setup-node@v3
      with:
        node-version: '22'   # You can also use 20 if you want latest

    - name: Install AWS CDK CLI
      run: npm install -g aws-cdk

    - name: Install Python dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt
      
    - name: CDK Synth
      run: |
        source .venv/bin/activate
        cdk synth
      
    - name: CDK diff
      run: | 
        source .venv/bin/activate
        cdk diff

    - name: CDK Bootstrap
      run: |
        source .venv/bin/activate
        cdk bootstrap

    - name: CDK Deploy
      run: |
        source .venv/bin/activate
        cdk deploy --require-approval never
