name: Deploy Python CDK
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Node.js (for CDK CLI)
      uses: actions/setup-node@v3
      with:
        node-version: '22'   # You can also use 20 if you want latest

    - name: Install AWS CDK CLI
      run: npm install -g aws-cdk

    - name: Install Python dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt

    - name: Verify CDK version
      run: cdk --version

    - name: CDK Bootstrap
      run: |
        source .venv/bin/activate
        cdk bootstrap aws://459685751152/ap-south-1

    - name: CDK Deploy
      run: |
        source .venv/bin/activate
        cdk deploy --require-approval never
